--19522064_NGUYENTHIMAIPHUONG--
--DE 02 --

-- TAO BANG (CAU 1, CAU 2)
CREATE TABLE BaiTapTH02.USER_NEW
(
    UIDS NUMBER(3) CONSTRAINT PK_USER_NEW PRIMARY KEY,
    USERNAME VARCHAR2(10),
    PASS VARCHAR2(10),
    REGDAY DATE,
    NATIONALITY VARCHAR2(15)
)
--DROP TABLE BaiTapTH02.USER_NEW
CREATE TABLE BaiTapTH02.CHANNEL
(
    CHANNELID VARCHAR2(4) CONSTRAINT PK_CHANNEL PRIMARY KEY,
    CNAME VARCHAR2(20),
    SUBSCRIBES NUMBER(4),
    OWNNER NUMBER(3),
    CREATED DATE
)

CREATE TABLE BaiTapTH02.VIDEO
(
    VIDEOID VARCHAR2(7) CONSTRAINT PK_VIDEO PRIMARY KEY,
    TITLE VARCHAR(60),
    DURATION NUMBER,
    AGE NUMBER
)

CREATE TABLE BaiTapTH02.SHARE_NEW
(
    VIDEOID VARCHAR2(7),
    CHANNELID VARCHAR2(4),
    CONSTRAINT PK_SHARE_NEW PRIMARY KEY(VIDEOID,CHANNELID)
)

-- INSERT DATA
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapTH02.USER_NEW VALUES ('001','faptv', '123456abc', '01/01/2014' ,'Vi?t Nam');
INSERT INTO BaiTapTH02.USER_NEW VALUES ('002', 'kemxoitv', '@147869ii', '05/06/2015', 'Campuchia');
INSERT INTO BaiTapTH02.USER_NEW VALUES ('003', 'openshare', 'qwertyuiop', '12/05/2009', 'Vi?t Nam');
SELECT *FROM BaiTapTH02.USER_NEW;

INSERT INTO BaiTapTH02.CHANNEL VALUES ('C120' ,'FAP TV', '2343', '001', '02/01/2014');
INSERT INTO BaiTapTH02.CHANNEL VALUES ('C905', 'Kem xôi TV' ,'1032', '002' ,'09/07/2015');
INSERT INTO BaiTapTH02.CHANNEL VALUES ('C357' ,'OpenShare Cáfe', '5064', '003', '10/12/2010');
SELECT *FROM BaiTapTH02.CHANNEL;

INSERT INTO BaiTapTH02.VIDEO VALUES('V100229', 'FAPtv C?m Ngu?i T?p 41 - ??t Nh?p', '469', '18');
INSERT INTO BaiTapTH02.VIDEO VALUES('V211002', 'Kem xôi: T?p 31 - M?y Kool tình yêu c?a anh', '312','16');
INSERT INTO BaiTapTH02.VIDEO VALUES('V400002', 'N?i tình yêu k?t thúc - Hoàng Tu?n', '378', '0');
SELECT *FROM BaiTapTH02.VIDEO;

INSERT INTO BaiTapTH02.SHARE_NEW VALUES('V100229', 'C905');
INSERT INTO BaiTapTH02.SHARE_NEW VALUES('V211002' ,'C120');
INSERT INTO BaiTapTH02.SHARE_NEW VALUES('V400002', 'C357');
SELECT *FROM BaiTapTH02.SHARE_NEW;

--KHOA NGOAI
ALTER TABLE BaiTapTH02.SHARE_NEW 
ADD CONSTRAINT SHARE_NEW_FN_1 FOREIGN KEY (VIDEOID) REFERENCES BaiTapTH02.VIDEO (VIDEOID);
ALTER TABLE BaiTapTH02.SHARE_NEW 
ADD CONSTRAINT SHARE_NEW_FN_2 FOREIGN KEY (CHANNELID) REFERENCES BaiTapTH02.CHANNEL (CHANNELID);

-- CAU 3:
CREATE OR REPLACE TRIGGER USER_NEW
BEFORE INSERT ON BaiTapTH02.USER_NEW
FOR EACH ROW
BEGIN
    :NEW.REGDAY :=SYSDATE;
END;

-- CAU 5
SELECT *
FROM BaiTapTH02.VIDEO
WHERE AGE>=16;

--  CAU 6:
SELECT  *
FROM BaiTapTH02.CHANNEL
WHERE SUBSCRIBES = (
    SELECT MAX(SUBSCRIBES) FROM BaiTapTH02.CHANNEL
);

--CAU 7:
SELECT VD.VIDEOID, COUNT(CHANNELID) TONG
FROM BaiTapTH02.VIDEO VD, BaiTapTH02.SHARE_NEW SH
WHERE VD.VIDEOID=SH.VIDEOID AND VD.AGE>=18
GROUP BY VD.VIDEOID;

--CAU 8: 
SELECT * 
FROM BaiTapTH02.VIDEO VD
WHERE NOT EXISTS
(
    SELECT *
    FROM BaiTapTH02.CHANNEL CHANN
    WHERE NOT EXISTS
    (
        SELECT * 
        FROM BaiTapTH02.SHARE_NEW SH
        WHERE SH.CHANNELID = CHANN.CHANNELID 
            AND SH.VIDEOID = VD.VIDEOID
    )
)




    
    