--19522064_NGUYENTHIMAIPHUONG--
--DE 01--


-- tao bang (cau 1, cau 2)
CREATE TABLE BaiTapTH01.XE
( 
    MAXE VARCHAR2(3) CONSTRAINT PK_XE  PRIMARY KEY,
    BIENKS VARCHAR2(9),
    MATUYEN VARCHAR2(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER  
)
--DROP TABLE BaiTapTH01.XE
-- tao bang TUYEN
CREATE TABLE BaiTapTH01.TUYEN
(
    MATUYEN VARCHAR2(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR2(3) NOT NULL,
    BENCUOI VARCHAR2(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)

--TAO BANG KHACH
CREATE TABLE BaiTapTH01.KHACH
(
    MAKH VARCHAR2(4) CONSTRAINT PK_MAKH PRIMARY KEY,
    HOTEN VARCHAR2(30),
    GIOITINH VARCHAR2(3),
    CMND NUMBER(11)
)

--TAO BANG VE XE
CREATE TABLE BaiTapTH01.VEXE
(
    MATUYEN VARCHAR2(4),
    MAKH VARCHAR2(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN,MAKH)
)

--INSERT DATA
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapTH01.XE VALUES ('X01', '52LD-4393', 'T11A', '20', '20');
INSERT INTO BaiTapTH01.XE VALUES ('X02', '59LD-7247', 'T32D', '36', '36');
INSERT INTO BaiTapTH01.XE VALUES ('X03', '55LD-6850', 'T06F', '15', '15');
SELECT *FROM BaiTapTH01.XE;

INSERT INTO BaiTapTH01.TUYEN VALUES ('T11A', 'SG', 'DL', '210000','26/12/2016', '6');
INSERT INTO BaiTapTH01.TUYEN VALUES ('T32D', 'PT', 'SG', '120000','30/12/2016', '4');
INSERT INTO BaiTapTH01.TUYEN VALUES ('T06F', 'NT', 'DNG', '225000','02/01/2017', '6');
SELECT *FROM BaiTapTH01.TUYEN;

INSERT INTO BaiTapTH01.KHACH VALUES ('KH01', 'LAM VAN BEN', 'NAM', '655615896');
INSERT INTO BaiTapTH01.KHACH VALUES ('KH02', 'DUONG THI LUC', 'NU', '27564862');
INSERT INTO BaiTapTH01.KHACH VALUES ('KH03', 'HOANG THANH TUNG', 'NAM', '456889143');
SELECT *FROM BaiTapTH01.KHACH;

INSERT INTO BaiTapTH01.VEXE VALUES ('T11A', 'KH01', '20/12/2016', '210000');
INSERT INTO BaiTapTH01.VEXE VALUES ('T32D', 'KH02', '25/12/2016', '144000');
INSERT INTO BaiTapTH01.VEXE VALUES ('T06F', 'KH03', '30/12/2016', '270000');
SELECT *FROM BaiTapTH01.VEXE;

--KHOA NGOAI
ALTER TABLE BaiTapTH01.XE
ADD CONSTRAINT XE_FN FOREIGN KEY (MATUYEN) REFERENCES BaiTapTH01.TUYEN (MATUYEN);
ALTER TABLE BaiTapTH01.VEXE 
ADD CONSTRAINT VX_FN_1 FOREIGN KEY (MATUYEN) REFERENCES BaiTapTH01.TUYEN (MATUYEN);
ALTER TABLE BaiTapTH01.VEXE 
ADD CONSTRAINT KHACH_FN FOREIGN KEY (MAKH) REFERENCES BaiTapTH01.VEXE (MAKH);
--Cau3: 
ALTER TABLE BaiTapTH01.TUYEN 
ADD CONSTRAINT GIA_TUYEN_CHECK CHECK(TGDK >5 AND GIATUYEN>200000)
ENABLE NOVALIDATE;
--INSERT INTO BaiTapTH01.TUYEN VALUES ('T11B', 'SG', 'DL', '600000','26/12/2016', '6');
--Câu 5:  
SELECT *
FROM BaiTapTH01.VEXE
WHERE EXTRACT(MONTH FROM(NGMUA))=12
ORDER BY GIAVE DESC;

-- 6. 
SELECT MATUYEN
FROM BaiTapTH01.VEXE
WHERE EXTRACT (YEAR FROM(NGMUA))=2016
GROUP BY MATUYEN
HAVING COUNT(MATUYEN)<= ALL
    (
        SELECT COUNT(MATUYEN)
        FROM BaiTapTH01.VEXE
        WHERE EXTRACT(YEAR FROM(NGMUA))=2016
        GROUP BY MATUYEN
    );

--7.
SELECT BaiTapTH01.TUYEN.MATUYEN
FROM BaiTapTH01.TUYEN, BaiTapTH01.VEXE, BaiTapTH01.KHACH
WHERE VEXE.MATUYEN=TUYEN.MATUYEN AND VEXE.MAKH=KHACH.MAKH
AND GIOITINH='Nam'
INTERSECT
SELECT BaiTapTH01.TUYEN.MATUYEN
FROM BaiTapTH01.TUYEN, BaiTapTH01.VEXE, BaiTapTH01.KHACH
WHERE VEXE.MATUYEN=TUYEN.MATUYEN AND VEXE.MAKH=KHACH.MAKH
AND GIOITINH='Nu';

--8. 
SELECT *
FROM BaiTapTH01.KHACH KH
WHERE GIOITINH='Nu' AND NOT EXISTS
    (
        SELECT *
        FROM BaiTapTH01.TUYEN TU
        WHERE NOT EXISTS 
        (
            SELECT *
            FROM BaiTapTH01.VEXE VX
            WHERE VX.MATUYEN=TU.MATUYEN AND VX.MAKH=KH.MAKH
        )
    )



